### PR TITLE
Adding Missing jQuery Map File.

### PR DESCRIPTION
**Pull request by astorm**
Addresses issue 

https://github.com/redlightblinking/b-responsive/issues/13

### CODE REVIEW

**Comment by philwinkle** [comment]
Duplicate of #14

**Comment by astorm** [comment]
Added this so the pull request points to the right branch.

**Comment by philwinkle** [comment]
:+1:  - didn't realize there was a dev branch. @magentogirl can pick whichever is more convenient lol.

**Comment by philwinkle** [comment]
You merged this to the ce-fixes branch and closed my PR - however - this is still a problem in the EE version. My PR was against the master branch - if you have no plans to merge the CE fixes upstream to master you should consider reopening my PR and merge to master for a once-and-final fix.

**Pull request merged**
